apiVersion: apps/v1
kind: Deployment
metadata:
  name: renting-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: renting
  template:
    metadata:
      labels:
        app: renting
    spec:
      containers:
      - name: renting-service
        image: renting-service
        ports:
        - containerPort: 5002
