apiVersion: v1
kind: Service
metadata:
  name: renting-service
spec:
  selector:
    app: renting
  ports:
    - protocol: TCP
      port: 6002
      targetPort: 5002
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: renting-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: renting
  template:
    metadata:
      labels:
        app: renting
    spec:
      containers:
      - name: renting-service
        image: srveerla/renting-service
        ports:
        - containerPort: 5002
